#!/bin/sh
# shellcheck disable=SC2034
readonly SCRIPT_NAME="dn-vnstat"
readonly SCRIPT_DIR="/jffs/addons/$SCRIPT_NAME.d"

if [ -f /opt/etc/init.d/S32vnstat ]; then
	/opt/etc/init.d/S32vnstat stop
	rm -f /opt/etc/init.d/S32vnstat
fi

if [ "$1" = "start" ] || [ "$1" = "restart" ]; then
	if [ -f "$SCRIPT_DIR/vnstat.conf" ]; then
		IFACE="$(grep "Interface " "$SCRIPT_DIR/vnstat.conf" | awk '{print $2}' | sed 's/"//g')"
		logger -st "vnstat" "Starting monitoring for interface $IFACE"
	else
		logger -st "vnstat" "Configuration file missing - $SCRIPT_DIR/vnstat.conf - please check"
		exit 1
	fi
	
	if [ "$(nvram get ntp_ready)" -eq 0 ]; then
		logger -st "vnstat" "NTP not synced, exiting"
		exit 1
	fi
	
	[ "$(ls -A /opt/var/lib/vnstat 2>/dev/null)" ] || vnstat --config "$SCRIPT_DIR/vnstat.conf" -u -i "$IFACE"
fi

TZ=$(cat /etc/TZ)
export TZ

ENABLED=yes
PROCS=vnstatd
ARGS="-d --config $SCRIPT_DIR/vnstat.conf"
PREARGS=""
DESC="$PROCS"
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
